const Currencies = [
    { code: 'AED', label: 'UAE Dirham', country: 'United Arab Emirates' },
    { code: 'AFN', label: 'Afghan Afghani', country: 'Afghanistan' },
    { code: 'ALL', label: 'Albanian Lek', country: 'Albania' },
    { code: 'AMD', label: 'Armenian Dram', country: 'Armenia' },
    { code: 'ANG', label: 'Netherlands Antillian Guilder', country: 'Netherlands Antilles' },
    { code: 'AOA', label: 'Angolan Kwanza', country: 'Angola' },
    { code: 'ARS', label: 'Argentine Peso', country: 'Argentina' },
    { code: 'AUD', label: 'Australian Dollar', country: 'Australia' },
    { code: 'AWG', label: 'Aruban Florin', country: 'Aruba' },
    { code: 'AZN', label: 'Azerbaijani Manat', country: 'Azerbaijan' },
    { code: 'BAM', label: 'Bosnia and Herzegovina Mark', country: 'Bosnia and Herzegovina' },
    { code: 'BBD', label: 'Barbados Dollar', country: 'Barbados' },
    { code: 'BDT', label: 'Bangladeshi Taka', country: 'Bangladesh' },
    { code: 'BGN', label: 'Bulgarian Lev', country: 'Bulgaria' },
    { code: 'BHD', label: 'Bahraini Dinar', country: 'Bahrain' },
    { code: 'BIF', label: 'Burundian Franc', country: 'Burundi' },
    { code: 'BMD', label: 'Bermudian Dollar', country: 'Bermuda' },
    { code: 'BND', label: 'Brunei Dollar', country: 'Brunei' },
    { code: 'BOB', label: 'Bolivian Boliviano', country: 'Bolivia' },
    { code: 'BRL', label: 'Brazilian Real', country: 'Brazil' },
    { code: 'BSD', label: 'Bahamian Dollar', country: 'Bahamas' },
    { code: 'BTN', label: 'Bhutanese Ngultrum', country: 'Bhutan' },
    { code: 'BWP', label: 'Botswana Pula', country: 'Botswana' },
    { code: 'BYN', label: 'Belarusian Ruble', country: 'Belarus' },
    { code: 'BZD', label: 'Belize Dollar', country: 'Belize' },
    { code: 'CAD', label: 'Canadian Dollar', country: 'Canada' },
    { code: 'CDF', label: 'Congolese Franc', country: 'Democratic Republic of the Congo' },
    { code: 'CHF', label: 'Swiss Franc', country: 'Switzerland' },
    { code: 'CLP', label: 'Chilean Peso', country: 'Chile' },
    { code: 'CNY', label: 'Chinese Renminbi', country: 'China' },
    { code: 'COP', label: 'Colombian Peso', country: 'Colombia' },
    { code: 'CRC', label: 'Costa Rican Colon', country: 'Costa Rica' },
    { code: 'CUP', label: 'Cuban Peso', country: 'Cuba' },
    { code: 'CVE', label: 'Cape Verdean Escudo', country: 'Cape Verde' },
    { code: 'CZK', label: 'Czech Koruna', country: 'Czech Republic' },
    { code: 'DJF', label: 'Djiboutian Franc', country: 'Djibouti' },
    { code: 'DKK', label: 'Danish Krone', country: 'Denmark' },
    { code: 'DOP', label: 'Dominican Peso', country: 'Dominican Republic' },
    { code: 'DZD', label: 'Algerian Dinar', country: 'Algeria' },
    { code: 'EGP', label: 'Egyptian Pound', country: 'Egypt' },
    { code: 'ERN', label: 'Eritrean Nakfa', country: 'Eritrea' },
    { code: 'ETB', label: 'Ethiopian Birr', country: 'Ethiopia' },
    { code: 'EUR', label: 'Euro', country: 'European Union' },
    { code: 'FJD', label: 'Fiji Dollar', country: 'Fiji' },
    { code: 'FKP', label: 'Falkland Islands Pound', country: 'Falkland Islands' },
    { code: 'FOK', label: 'Faroese Króna', country: 'Faroe Islands' },
    { code: 'GBP', label: 'Pound Sterling', country: 'United Kingdom' },
    { code: 'GEL', label: 'Georgian Lari', country: 'Georgia' },
    { code: 'GGP', label: 'Guernsey Pound', country: 'Guernsey' },
    { code: 'GHS', label: 'Ghanaian Cedi', country: 'Ghana' },
    { code: 'GIP', label: 'Gibraltar Pound', country: 'Gibraltar' },
    { code: 'GMD', label: 'Gambian Dalasi', country: 'The Gambia' },
    { code: 'GNF', label: 'Guinean Franc', country: 'Guinea' },
    { code: 'GTQ', label: 'Guatemalan Quetzal', country: 'Guatemala' },
    { code: 'GYD', label: 'Guyanese Dollar', country: 'Guyana' },
    { code: 'HKD', label: 'Hong Kong Dollar', country: 'Hong Kong' },
    { code: 'HNL', label: 'Honduran Lempira', country: 'Honduras' },
    { code: 'HRK', label: 'Croatian Kuna', country: 'Croatia' },
    { code: 'HTG', label: 'Haitian Gourde', country: 'Haiti' },
    { code: 'HUF', label: 'Hungarian Forint', country: 'Hungary' },
    { code: 'IDR', label: 'Indonesian Rupiah', country: 'Indonesia' },
    { code: 'ILS', label: 'Israeli New Shekel', country: 'Israel' },
    { code: 'IMP', label: 'Manx Pound', country: 'Isle of Man' },
    { code: 'INR', label: 'Indian Rupee', country: 'India' },
    { code: 'IQD', label: 'Iraqi Dinar', country: 'Iraq' },
    { code: 'IRR', label: 'Iranian Rial', country: 'Iran' },
    { code: 'ISK', label: 'Icelandic Króna', country: 'Iceland' },
    { code: 'JEP', label: 'Jersey Pound', country: 'Jersey' },
    { code: 'JMD', label: 'Jamaican Dollar', country: 'Jamaica' },
    { code: 'JOD', label: 'Jordanian Dinar', country: 'Jordan' },
    { code: 'JPY', label: 'Japanese Yen', country: 'Japan' },
    { code: 'KES', label: 'Kenyan Shilling', country: 'Kenya' },
    { code: 'KGS', label: 'Kyrgyzstani Som', country: 'Kyrgyzstan' },
    { code: 'KHR', label: 'Cambodian Riel', country: 'Cambodia' },
    { code: 'KID', label: 'Kiribati Dollar', country: 'Kiribati' },
    { code: 'KMF', label: 'Comorian Franc', country: 'Comoros' },
    { code: 'KRW', label: 'South Korean Won', country: 'South Korea' },
    { code: 'KWD', label: 'Kuwaiti Dinar', country: 'Kuwait' },
    { code: 'KYD', label: 'Cayman Islands Dollar', country: 'Cayman Islands' },
    { code: 'KZT', label: 'Kazakhstani Tenge', country: 'Kazakhstan' },
    { code: 'LAK', label: 'Lao Kip', country: 'Laos' },
    { code: 'LBP', label: 'Lebanese Pound', country: 'Lebanon' },
    { code: 'LKR', label: 'Sri Lanka Rupee', country: 'Sri Lanka' },
    { code: 'LRD', label: 'Liberian Dollar', country: 'Liberia' },
    { code: 'LSL', label: 'Lesotho Loti', country: 'Lesotho' },
    { code: 'LYD', label: 'Libyan Dinar', country: 'Libya' },
    { code: 'MAD', label: 'Moroccan Dirham', country: 'Morocco' },
    { code: 'MDL', label: 'Moldovan Leu', country: 'Moldova' },
    { code: 'MGA', label: 'Malagasy Ariary', country: 'Madagascar' },
    { code: 'MKD', label: 'Macedonian Denar', country: 'North Macedonia' },
    { code: 'MMK', label: 'Burmese Kyat', country: 'Myanmar' },
    { code: 'MNT', label: 'Mongolian Tögrög', country: 'Mongolia' },
    { code: 'MOP', label: 'Macanese Pataca', country: 'Macau' },
    { code: 'MRU', label: 'Mauritanian Ouguiya', country: 'Mauritania' },
    { code: 'MUR', label: 'Mauritian Rupee', country: 'Mauritius' },
    { code: 'MVR', label: 'Maldivian Rufiyaa', country: 'Maldives' },
    { code: 'MWK', label: 'Malawian Kwacha', country: 'Malawi' },
    { code: 'MXN', label: 'Mexican Peso', country: 'Mexico' },
    { code: 'MYR', label: 'Malaysian Ringgit', country: 'Malaysia' },
    { code: 'MZN', label: 'Mozambican Metical', country: 'Mozambique' },
    { code: 'NAD', label: 'Namibian Dollar', country: 'Namibia' },
    { code: 'NGN', label: 'Nigerian Naira', country: 'Nigeria' },
    { code: 'NIO', label: 'Nicaraguan Córdoba', country: 'Nicaragua' },
    { code: 'NOK', label: 'Norwegian Krone', country: 'Norway' },
    { code: 'NPR', label: 'Nepalese Rupee', country: 'Nepal' },
    { code: 'NZD', label: 'New Zealand Dollar', country: 'New Zealand' },
    { code: 'OMR', label: 'Omani Rial', country: 'Oman' },
    { code: 'PAB', label: 'Panamanian Balboa', country: 'Panama' },
    { code: 'PEN', label: 'Peruvian Sol', country: 'Peru' },
    { code: 'PGK', label: 'Papua New Guinean Kina', country: 'Papua New Guinea' },
    { code: 'PHP', label: 'Philippine Peso', country: 'Philippines' },
    { code: 'PKR', label: 'Pakistani Rupee', country: 'Pakistan' },
    { code: 'PLN', label: 'Polish Złoty', country: 'Poland' },
    { code: 'PYG', label: 'Paraguayan Guaraní', country: 'Paraguay' },
    { code: 'QAR', label: 'Qatari Riyal', country: 'Qatar' },
    { code: 'RON', label: 'Romanian Leu', country: 'Romania' },
    { code: 'RSD', label: 'Serbian Dinar', country: 'Serbia' },
    { code: 'RUB', label: 'Russian Ruble', country: 'Russia' },
    { code: 'RWF', label: 'Rwandan Franc', country: 'Rwanda' },
    { code: 'SAR', label: 'Saudi Riyal', country: 'Saudi Arabia' },
    { code: 'SBD', label: 'Solomon Islands Dollar', country: 'Solomon Islands' },
    { code: 'SCR', label: 'Seychellois Rupee', country: 'Seychelles' },
    { code: 'SDG', label: 'Sudanese Pound', country: 'Sudan' },
    { code: 'SEK', label: 'Swedish Krona', country: 'Sweden' },
    { code: 'SGD', label: 'Singapore Dollar', country: 'Singapore' },
    { code: 'SHP', label: 'Saint Helena Pound', country: 'Saint Helena' },
    { code: 'SLL', label: 'Sierra Leonean Leone', country: 'Sierra Leone' },
    { code: 'SOS', label: 'Somali Shilling', country: 'Somalia' },
    { code: 'SRD', label: 'Surinamese Dollar', country: 'Suriname' },
    { code: 'SSP', label: 'South Sudanese Pound', country: 'South Sudan' },
    { code: 'STN', label: 'São Tomé and Príncipe Dobra', country: 'São Tomé and Príncipe' },
    { code: 'SYP', label: 'Syrian Pound', country: 'Syria' },
    { code: 'SZL', label: 'Eswatini Lilangeni', country: 'Eswatini' },
    { code: 'THB', label: 'Thai Baht', country: 'Thailand' },
    { code: 'TJS', label: 'Tajikistani Somoni', country: 'Tajikistan' },
    { code: 'TMT', label: 'Turkmenistan Manat', country: 'Turkmenistan' },
    { code: 'TND', label: 'Tunisian Dinar', country: 'Tunisia' },
    { code: 'TOP', label: 'Tongan Paʻanga', country: 'Tonga' },
    { code: 'TRY', label: 'Turkish Lira', country: 'Turkey' },
    { code: 'TTD', label: 'Trinidad and Tobago Dollar', country: 'Trinidad and Tobago' },
    { code: 'TVD', label: 'Tuvaluan Dollar', country: 'Tuvalu' },
    { code: 'TWD', label: 'New Taiwan Dollar', country: 'Taiwan' },
    { code: 'TZS', label: 'Tanzanian Shilling', country: 'Tanzania' },
    { code: 'UAH', label: 'Ukrainian Hryvnia', country: 'Ukraine' },
    { code: 'UGX', label: 'Ugandan Shilling', country: 'Uganda' },
    { code: 'USD', label: 'United States Dollar', country: 'United States' },
    { code: 'UYU', label: 'Uruguayan Peso', country: 'Uruguay' },
    { code: 'UZS', label: 'Uzbekistani Som', country: 'Uzbekistan' },
    { code: 'VES', label: 'Venezuelan Bolívar', country: 'Venezuela' },
    { code: 'VND', label: 'Vietnamese Đồng', country: 'Vietnam' },
    { code: 'VUV', label: 'Vanuatu Vatu', country: 'Vanuatu' },
    { code: 'WST', label: 'Samoan Tālā', country: 'Samoa' },
    { code: 'XAF', label: 'Central African CFA Franc', country: 'Central Africa' },
    { code: 'XCD', label: 'East Caribbean Dollar', country: 'East Caribbean' },
    { code: 'XOF', label: 'West African CFA Franc', country: 'West Africa' },
    { code: 'XPF', label: 'CFP Franc', country: 'French territories of the Pacific' },
    { code: 'YER', label: 'Yemeni Rial', country: 'Yemen' },
    { code: 'ZAR', label: 'South African Rand', country: 'South Africa' },
    { code: 'ZMW', label: 'Zambian Kwacha', country: 'Zambia' },
    { code: 'ZWL', label: 'Zimbabwean Dollar', country: 'Zimbabwe' },
];

export default Currencies;
